---
title: "Assignment 1: Introduction"
author: "Rachael Stephan"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have some training with R through my undergraduate degree. There was some basic introductory labs on the program and a more advanced class on data analysis on scientific statistics (e.g., likelihood, models, etc.). I taught myself a little bit of ggplot2, but it was very rudimentary. I completed an undergraduate thesis in which I conducted my statistical analysis and created graphs in RStudio. I have no experience with git. 

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident that I will be able to navigate online and course resources to learn about R and Git where I am lacking. I am confident that I have a decent base to build analytical skills off of. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
